import os
import logging
import numpy as np
import pandas as pd
from PIL import Image
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms.functional import to_tensor
from torchvision.transforms import Compose
from typing import List, Tuple, Dict
from dataclasses import dataclass
from enum import Enum
from abc import ABC, abstractmethod
from scipy import ndimage
from scipy import signal
from scipy import stats
from scipy import optimize
from scipy import spatial
from scipy import interpolate
from scipy import ndimage
import cv2
import math
import random
import string
import json
import yaml
import pickle
import torch
import torchvision
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.patches as patches
import matplotlib.colors as mcolors
import matplotlib.cm as cm
import matplotlib as mpl
import matplotlib.backends.backend_tkagg as tkagg
import matplotlib.figure as figure
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_tkagg as